---
name: my first ci
on:
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: echo "starting ci...."
      - name: show date
        run: date
      - name: done
        run: echo "ci complete"