---
name: "jobs in github actions"
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
  workflow_dispatch:
    inputs:
      environment:
        description: 'first job for scanning packages and syntax'
        required: true
        default: dependencies
        type: choice
        options:
          - syntax
          - dependencies
          - full
jobs:
  scanning:
    runs-on: ubuntu-latest
    steps:
      - name: load code
        uses: actions/checkout@v4
      - name: installing dependencies
        run: npm ci
      - name: syntax check
        if: ${{ github.event.inputs.environment == 'syntax'}}
        run: |
          npx tsc --noEmit
          npm run lint
      - name: checking dependencies
        if: ${{ github.event.inputs.environment == 'dependencies'}}
        run: |
          npm audit
          npm outdated
      - name: full scanning
        if: >
          ${{ github.event.inputs.environment == 'full'
          || github.event_name == 'pull_request'  }}
        run: |
          npx tsc --noEmit
          npm run lint
          npm audit
          npm outdated